### ISSUE TITLE
The debugger doesn't work with nrepl-sync-request:eval

### ISSUE THREAD

**Issue by abo-abo** [clojure-emacs/cider#1052]
It appears that the debugger only works with `nrepl-request:eval` currently (that's what `cider-interactive-eval` uses).

Could we get support for `nrepl-sync-request:eval` as well? Currently, it just times out.

**Comment by Malabarba** [comment]
What does `sync-request:eval` do? From the name, I suppose it forces Emacs to wait for a response.
Does it have to wait until `"done"` is received? Or will any response do?

Synchronous debugging should be doable on regular top-level forms, but I can't imagine how it would be done with functions. And I should warn you we were thinking of implementing an operation specifically for the debugger, so it would no longer use `"eval"` at all, and that might make this feature harder to achieve.

**Comment by bbatsov** [comment]
> What does sync-request:eval do? From the name, I suppose it forces Emacs to wait for a response.
> Does it have to wait until "done" is received? Or will any response do?

It waits for `done` or `status` if memory serves. Or timeouts if nothing happens for a configurable sync timeout duration. 

> Could we get support for nrepl-sync-request:eval as well? Currently, it just times out.

What's your use case?

**Comment by abo-abo** [comment]
> It waits for done or status if memory serves

With the new debugger, there's also "need-input", where it bugs out. To the point where I have to restart the REPL.

> What's your use case?

The use case is [lispy](https://github.com/abo-abo/lispy/blob/master/le-clojure.el#L82) and `org-babel-execute:clojure`.
Both do stuff with the value of the sync eval.
The async eval looks to be very inconvenient, since it needs 5 callback functions for each use case.
In `lispy` there are many use cases:

- plain eval: the standard output is concatenated with the value, so async doesn't work, since it has
separate callbacks for stdout and value
- eval and insert
- eval and commented insert
- eval and replace
- eval and flatten
- eval and show function doc
- eval and show function args

I'm fine with the easy solution of immediately returning a bad status for sync eval when
"need-input" is encountered.
But it would be pretty cool if it actually went through and the function that called sync eval
would be kept waiting until the debugger exited.

> And I should warn you we were thinking of implementing an operation specifically for the debugger,
> so it would no longer use "eval" at all, and that might make this feature harder to achieve.

I think it's worth to put in more work to get a better thing, and I'm glad that you did.

**Comment by Malabarba** [comment]
> I agree. I tried to fix it yesterday but just immediately returning on "need-input", but I still get the REPL in an unresponsive state. Maybe you could look into it.

Simply returning won't work because the repl will still be waiting for input. The safest thing to do is to forward this input request to the user. Check out nrepl-make-response-handler, to see how need-input is handled.

Things went sort of unexpectedly wrong here at work, so I won't have time to look into this for a while.

**Comment by bbatsov** [comment]
Fixed in #1074.

**Comment by abo-abo** [comment]
The debugger issue is back with the latest code. To reproduce, instrument this:

```clojure
(defn square [x]
  (* x x))
  ```

And evaluate this:

```elisp
(nrepl-sync-request:eval "(map square '(1 2 3))")
```

Also, I can't reopen this issue.

**Comment by Malabarba** [comment]
Ah yes, since a while ago the debugger's code no longer uses stdin for input requests, so I can see why this breaks. I'll try to think of a solution. @bbatsov Could you open this again?

**Comment by bbatsov** [comment]
Done.
