### ISSUE TITLE
Debug does not work from *cider-scratch*

### ISSUE THREAD

**Issue by mobius-eng** [clojure-emacs/cider#1312]
If function is defined in `*cider-scratch*`, for example

```
(defn factorial [n]
  (if (< n 1)
    1
    (* n (factorial (dec n)))))
```

Doing `C-u C-M-x` evaluates it without the problem. But if the expression

```
(factorial 3)
```

is evaluated (either in `*cider-scratch*` (with either `C-j` or `C-x C-e`) or in REPL), it produces an error:

```
Error encountered while handling the debug message: (wrong-type-argument arrayp nil)
```

If the same function is in a proper file in the project, debugging proceeds normally.

If the function definition is evaluated without debugging, `(factorial 3)` evaluates to 6 without error

CIDER 0.10.0-SNAPSHOT
CIDER-nREPL 0.10.0-SNAPSHOT
tools.nrepl 0.2.10

Emacs 24.5 on Mac OS X 10.10

**Comment by Malabarba** [comment]
Yes I had that too. I pushed a fix yesterday so it should be on Melpa already. 
Could you try again with the latest version?

**Comment by mobius-eng** [comment]
Updated CIDER today from Melpa (10-Sep): the issue is still there.

**Comment by mobius-eng** [comment]
Update: I didn't restart Emacs (though just restarting CIDER would be sufficient), so it didn't work. After Emacs restart it works.

**Comment by Malabarba** [comment]
FTR, you always need to restart emacs to see the effects of an upgrade. (or you can reload the files, if you know how to do that).

**Comment by bbatsov** [comment]
Guess we should add this to the troubleshooting section of the readme.
