### ISSUE TITLE
Debugger flickers if it was triggered by a sync-eval

### ISSUE THREAD

**Issue by sooheon** [clojure-emacs/cider#1589]
## Expected behavior

Stepping through in `cider-debug` should not flicker overlays.
## Actual behavior

Calling `continue` causes flicker of overlays.

I saw a brief mention of flicker by @Malabarba, but he seemed to be saying it was fine on his machine--is this a performance issue, then? One thing I noticed is that there is no flicker when using the `-nw` flag. 

![debug-flicker](https://cloud.githubusercontent.com/assets/302945/13342186/704b9f22-dc82-11e5-90be-c90344602356.gif)
## Steps to reproduce the problem
1. emacs -Q
2. (package-initialize)
3. Simply call `cider-debug-defun-at-point`, call the function with some arg, and step through.
### CIDER version information

CIDER 0.11.0snapshot (package: 20160225.716) (Java 1.8.0_60, Clojure 1.7.0, nREPL 0.2.12)
### Emacs version

GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0, NS apple-appkit-1404.34) of 2016-01-15 on Icarus
### Operating system

OSX El Capitan

**Comment by Malabarba** [comment]
> I saw a brief mention of flicker by @Malabarba, but he seemed to be saying it was fine on his machine--is this a performance issue, then? 

No, it was a regression I introduced, but I also fixed it afterwards.
Does it flicker when you step `next` (instead of `continue`), or is it just with `continue`?

**Comment by sooheon** [comment]
Ah I was imprecise in the original report: It happens with `n`, `c`, `o`, and on pressing `e` the overlay disappears while the prompt for expression is active.

**Comment by bbatsov** [comment]
I can confirm the flicker is still present, although it doesn't happen all the time as before. Try debugging this:

```
(defn greet [name]
  (println (greeting name)))
```
I get a flicker only after the second `n`.

**Comment by Malabarba** [comment]
I tried reproducing this with the following code, but I don't see any flicker.

```clj
(defn greeting [s]
  (format "LALAL %s" s))

(defn greet [s]
  (println (greeting s)))

(greet "ama")
```

In a blind attempt to fix this, I've increased the timeout we use on `accept-process-output`. Let me know if it has any effect.

**Comment by bbatsov** [comment]
I can't reproduce this every time myself. Let's see what @sooheon will say.

**Comment by sooheon** [comment]
I see now that this was caused by an interaction with `lispy-mode`. It matters how the debugger is entered. After calling `cider-debug-defun-at-point` on `greeting` and `greet`:

1. calling `cider-eval-last-sexp` on `(greet "ama")` and stepping through debugger with `n` does not flicker (or rarely, hard to reproduce). accept-process-output delay doesn't seem to make a difference.

2. calling `special-lispy-eval` on `(greet "ama")` will flicker every time.

So it may no longer be an issue for cider, in which case feel free to close the issue. But if any insight can be offered now that its narrowed down, that would help me in making a useful report for the lispy repo :)

**Comment by Malabarba** [comment]
>  But if any insight can be offered now that its narrowed down, that would help me in making a useful report for the lispy repo :)

If `special-lispy-eval` uses sync requests, then that could have something to do with it. The debugger avoids the flicker by waiting for process output after sending they key you hit but before erasing the overlays. Since sync requests also involve waiting for input, it's possible that those two get messed up, and we end up erasing the overlays before the process-output arrives.

**Comment by sooheon** [comment]
What is your take on this @abo-abo ?

**Comment by abo-abo** [comment]
@sooheon In my opinion, `lispy` should keep do eval requests in sync for now. It greatly simplifies debugging and allows easy evaluation of everything (not just Clojure).

Just a suggestion to @Malabarba, I expect it will be a lot easier to code CIDER if you used sync evaluation requests. Is there any fundamental reason to go async?

**Comment by Malabarba** [comment]
> Just a suggestion to @Malabarba, I expect it will be a lot easier to code CIDER if you used sync evaluation requests. Is there any fundamental reason to go async?

I don't know why it was made like this, maybe @bbatsov does. 
If I were to give a (not so thought-out) opinion, I'd say that asynchronicity has complicated my life more than it helped. But I'm not about to put it the necessary effort to switch over. :-P

**Comment by bbatsov** [comment]
The reason is quite simple - there are no sync requests in nREPL (we've added the concept of sync requests relatively late when it was clear that Elisp is not very async-friendly - e.g. in many places we'd have several nested callbacks). Also if streaming results you really want to go async, otherwise you'd have to wait until a request is fully finished which might be quite a while.

**Comment by abo-abo** [comment]
@bbatsov I imagine CIDER as a construct on top of `lein repl`. And that thing, just like any other REPL I know is fully sync: you type in a request, it gets processed and the result is printed.

I get why one would want to make e.g. a `locate` interface async - since a large amount of data is coming in short bursts. But the output of a command into `lein repl` comes in a single sync echo, as far as I understand.

I also get why e.g. Jedi is async - since it displays async popups in auto-complete/company it has to be. But that async part can be isolated and sync can be used in all other places.  As an anecdote, I wanted to implement completion for Python's `from foo import <completion for all foo's syms here>`. After spending a lot of time figuring out `jedi.el`'s async stuff, I dropped it and implemented what I wanted in 15 lines with `python-shell-send-string-no-output`, which is basically a sync eval for Python.

**Comment by bbatsov** [comment]
> @bbatsov I imagine CIDER as a construct on top of lein repl. And that thing, just like any other REPL I know is fully sync: you type in a request, it gets processed and the result is printed.

CIDER has very little to do with `lein repl` - that's just one convenient way to boot an nREPL server. We never deal with console input/output directly. I get it that it's easier to program in terms of sync requests, but that's simply not an option for many things. At least we have some quasi-sync requests now - originally the plan was to have none such thing.

**Comment by Malabarba** [comment]
I've renamed this issue. Regardless of the second conversation that was developed here, it is true that the debugger flickers on sync requests, and I definitely consider that a bug.

However, it's niche enough that I don't think I'll be prioritizing it any time soon, so I've marked it as help wanted in case anyone is bothered enough to try to fix it.

**Comment by sooheon** [comment]
Could you briefly outline what you think needs to be done to resolve this issue?

**Comment by Malabarba** [comment]
1. After the user presses one of the debug keys (providing input), we send that input to the clojure process.
2. Then, while we're shutting down all the debug stuff, there's a call to `(accept-process-output proc 1)` (it's inside `cider--debug-mode`). That hangs interface between debug steps, for up to 1 second (or until the next debug step arrives, which usually happens first).
3. Immediately after that, we call `cider--debug-remove-overlays`.
4. If some new process output has already arrived before that (due to `accept-process-output`), then Emacs will immediately proceed to handle the process output (without performing a redisplay).
5. If the new output that arrived was a debug step, then the debugger will recreate the overlays. 
6. Since all of that happened before Emacs had a chance to redisplay, the user doesn't notice that the old overlays were destroyed and replaced by new ones.

Now go back to step 5. If the new output that arrived was **not** a debug step, then the debugger doesn't immediately recreate the overlays. It will probably still recreate them in ~0.1 sec when we recive the actual debug message, but 0.1 sec is plenty of time for Emacs to do a redisplay. Now this redisplay happened after we destroyed the overlays but before we recreate them, so there's a visible flicker for the user.

That is currently my best guess for what's happening, but it's very possible I'm wrong.

The generic code for sync requests is in the function `nrepl-send-sync-request` in `nrepl-client.el`. Note how it also involves `(accept-process-output nil 0.01)`. So that could be another source of conflicts.

That's really I can think of right now. Sorry I can't be of more help. :-(

**Comment by vspinu** [comment]
Can someone post a clear reproducible example of this? I might look into this.
