### ISSUE TITLE
Fail to start nREPL

### ISSUE THREAD

**Issue by PiFlUn** [clojure-emacs/cider#2140]
## Expected behavior
Start the nREPL either by `M-x cider-jack-in` or `M-x cider-connect` (with lein repl running in the terminal, in the leiningen project folder).

## Actual behavior
nREPL server connects to localhost then connection closes due to "error in process filter".

## Steps to reproduce the problem
Start up emacs with an existing leininger project then try to run the nREPL by either by `M-x cider-jack-in` or `M-x cider-connect`.

## Environment & Version information
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12

### CIDER version information
*Include here the version string displayed when
CIDER's REPL is launched.*
Cannot provide due to error, version displayed by `M-x list-packages` 20171213.2315

### Lein/Boot version
Leiningen 2.8.1 on Java 1.8.0_151 OpenJDK 64-Bit Server VM

### Emacs version
GNU Emacs 24.5.1 

### Operating system
Ubuntu 16.04.3 LTS

### Full error message taken from `*Messages*` after `M-x cider-jack-in`
Starting nREPL server via /bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.4.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.16.0-SNAPSHOT\"\] -- repl :headless :host ::...
nREPL server started on 45727
[nREPL] Establishing direct connection to localhost:45727 ...
[nREPL] Direct connection to localhost:45727 established
error in process filter: cider--connections-refresh: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))
error in process filter: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))

### Full error message taken from `*Messages*` after `M-x cider-connect`

nREPL server started on 44116
[nREPL] Establishing direct connection to localhost:44116 ...
[nREPL] Direct connection to localhost:44116 established
error in process filter: cider--connections-refresh: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))
error in process filter: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))
[nREPL] Connection closed unexpectedly (connection broken by remote peer)
error in process sentinel: cider--connections-refresh: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))
error in process sentinel: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))
[nREPL] Establishing direct connection to localhost:41927 ...
[nREPL] Direct connection to localhost:41927 established
cider--connections-refresh: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))

**Comment by bbatsov** [comment]
Likely you've installed some broken snapshot - please, install the latest one and that should fix the problem.

**Comment by PiFlUn** [comment]
Thanks for tip. Now that I compared the problematic version with one on another computer where it works, I see the difference in the date.

**Comment by radirk** [comment]
I'm still getting this issue with snapshot 20171218.214. My setup is exactly the same as above, except I'm on Clojure 1.9 and lein 2.7.1

**Comment by xiongtx** [comment]
Lein 2.7.1 is pretty old; the latest release is [2.8.1](https://github.com/technomancy/leiningen/releases). Does this still occur after a `lein upgrade`?

**Comment by radirk** [comment]
Upgraded to lein 2.8.1. Still have the issue with latest snapshot 20171220.135. Will investigate further. Thanks!

**Comment by xiongtx** [comment]
Anything in your .lein/profile.clj?

**Comment by bherrmann7** [comment]
I was trying to create a new clojure 1.9 project (to give spec a spin)..   Was getting an error on "cider-jack-in" so I updated my cider package to the latest. (  I now also get the error above.   I also flipped back to a clojure 1.8 project - still broken.   I bumped my lein from 2.7.1 to 2.8.1 but no difference.    "$ lein repl" works fine.
...
[nREPL] Direct connection to localhost:33559 established
error in process filter: cider--connections-refresh: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))
error in process filter: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))

My cider is at,
 cider              20171220.135  installed             Clojure Interactive Development Environment that Rocks

**Comment by bbatsov** [comment]
I wonder if we didn't break compatibility with Emacs 24.x in some subtle way recently. Can't imagine what else could be causing such an error. 

```cider--connections-refresh: Invalid function: (buffer (get-buffer cider--connection-browser-buffer-name))```

**Comment by bherrmann7** [comment]
I'm running with Emacs 25.2.1 on Ubuntu 17.10

**Comment by bbatsov** [comment]
Did you try complete removing CIDER and installing again?

**Comment by bherrmann7** [comment]
I'm right now working using cider 0.15.1 and all is great, the error was happening when using cider 20171220.135  (initially this morning I was running a cider version from june.)  I deleted, installed the latest cider and had even restarted emacs.     But I consistently got the invalid function error.

**Comment by radirk** [comment]
Tried cleaning out ~/.m2/repository/cider, switching to 0.15.1 from 0.16.0-SNAPSHOT, upgrading everything in .lein/profiles.clj. Still no luck getting it to work.

**Comment by soulawaker** [comment]
I've stuck in same problem with same error messages after updating cider from 0.15.0-SNAPSHOT to 0.17.0-SNAPSHOT. My environment is same above except following components.

## Environment 
Oracle JDK 64bit 1.8.0_151

### CIDER version
package 20171228.1254

### Emacs version
Spacemacs based on GNU Emacs 24.5.1

### OS
Elementary OS Loki based on Ubuntu 16.04.

**Comment by soulawaker** [comment]
It worked. I missed this workaround. It's annoying that sometimes updating
packages has problems like this randomly. Thanks.

2017-12-29 19:57 GMT+09:00 Bozhidar Batsov <notifications@github.com>:

**Comment by harold** [comment]
Encountered this today on a machine that is still running Emacs24. Removing cider* from `.emacs.d` and starting Emacs again fixed it.

**Comment by the-frey** [comment]
Encountered this one today on emacs 24.5 - as @harold says, nuking cider and then `M-x package install cider` after restart seems to clear it up for some reason...

**Comment by PiFlUn** [comment]
Same happened to me today too - wanted to fire up cider again, did not start. Nuked cider, installed it again and whoosh it works again. 
Should I reopen the issue? I mean sure, everyone can solve it by him/herself though it would be nice in my opinion if a new version of cider would not cause problems like this.

**Comment by bbatsov** [comment]
It's not really a problem with CIDER - it's a problem with `package.el` and how it byte-compiles stuff. Sometimes something stale remains and this leads to such problems.
