### ISSUE TITLE
cider-inspect contents are truncated when clojure.core/*print-length* is set

### ISSUE THREAD

**Issue by bitti** [clojure-emacs/cider#2152]
## Expected behavior

The full object under inspection should be visible in *cider-inspect* buffer.

## Actual behavior

Depending on the `*print-length*` setting only about the first `*print-length*`/6 elements of the object under inspection are displayed. That also applies when inspecting subelements.

## Steps to reproduce the problem

```
user> (set! *print-length* 20)
20
user> (range 100)
```

Pressing C-c M-i (for cider-inspect) yields this inspect buffer:

```
Class: clojure.lang.LongRange
Contents: 
  0. 0
  1. 1
  2. 2...
```

When inspecting subelements the behaviors differ when I just set the `*print-length*` in the repl or already in `~/.lein/profiles.clj` (via `:global-vars { *print-length* 20 }` for the `repl` profile). In the former case when inspecting subelements the full element is displayed and when I go back with `l` to the top-level object the full object is shown this time. In the latter case it remains truncated. E.g. inspecting the second element yields then:

```
Type: java.lang.Long
Value: "1"
---
Fields: 
  "MIN_VALUE" = -9223372036854775808
  "MAX_VALUE" = ...
```

Even when I issue a `(set! *print-length* nil)` in the repl  (with an initial `*print-length*` set in `~/.lein/profiles.clj` that is) only the initial inspect buffer is untruncated but when inspecting a subelement or just switching a page it gets truncated again.

### CIDER version information

```
;; CIDER 0.17.0snapshot (package: 20180103.652), nREPL 0.2.13
;; Clojure 1.7.0, Java 1.8.0_151
```
Also tested with previous Cider Version 0.16.0snapshot and JDK 9.0.1 and Open-JDK 9.0.1.

### Lein version

Leiningen 2.8.1 on Java 1.8.0_151 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-06-20

### Operating system

Ubuntu 16.04.3 LTS
Linux 4.10.0-42-generic

**Comment by bitti** [comment]
I've got an idea what's going on: Clojure adheres the `*print-length*` option (and probably a few others) in quite a few standard print functions like `pr`, `prn`, `print`, `println`, `clojure.pprint/write`. If cider uses any of them internally they probably should be wrapped in a `(binding [*print-length* nil] ...)` form.

**Comment by bbatsov** [comment]
Yeah, I assumed as much when I saw this report. I just didn't have time to look at the code yet.

**Comment by bitti** [comment]
I found kind of a workaround by installing a nrepl-middleware via

        :repl-options {
                       :nrepl-middleware
                       [(fn [handler]
                          (fn [& args]
                            (binding [clojure.core/*print-length*
                                      (if (or ((first args) :pprint)
                                              (= ((first args) :op) "eval"))
                                        clojure.core/*print-length*)]
                              (apply handler args))))]
                       }

in `~/.lein/profiles.clj` for the `repl` environment. But it has two problems: 1. The `*print-length*` setting isn't adhered anymore when it set them in `profiles.clj` so I have to set it manually in the repl 2. The initial inspector window still shows truncated values, but when I press `g` for refresh the full values are shown. The initial display doesn't seem to go through the nrepl-middleware though, so there is nothing I could do about it. On the other hand it seems that cider has its own middleware, so probably a proper fix would have to be happen there.

**Comment by bbatsov** [comment]
I guess the fix needs to be applied here https://github.com/clojure-emacs/orchard/blob/master/src/orchard/inspect.clj#L221

You can play with this if you want.

**Comment by bitti** [comment]
That means I have to build orchard myself? But I just saw that you pushed a commit where *print-length* can be set as as a cider customization variable, maybe in this way the problem can be avoided in the first place? Is no one else able to reproduce the problem btw?

**Comment by bbatsov** [comment]
> But I just saw that you pushed a commit where print-length can be set as as a cider customization variable, maybe in this way the problem can be avoided in the first place?

Right now CIDER just sets the variable globally, so this changes nothing. For this to be avoided it should start wrapping evaluations in some "context" for the scope of each request. Probably that's the better solution, but it will take more time and I don't have time now.

**Comment by bbatsov** [comment]
I'm reasonably sure your problem is real, probably most people simply don't set any `*print-level*`. I just have a ton of work across the board and don't have time to debug and fix this myself.

**Comment by bitti** [comment]
I had to rollback to cider 0.16.0, since 0.17.0-SNAPSHOT was suddenly broken for me. But I still found the function, even though it was in another package (`cider.nrepl.middleware.util.inspect`). Doing a rebind there didn't had any effect, and also for all other functions I checked there `*print-length*` seems to be correctly set to `nil` during runtime. But as I said, currently the problem only occurs on the initial inspection window. Pressing `g` for refresh already fixes it.

**Comment by vspinu** [comment]
`*print-length*` affects `spit` btw, and breaks `slurp`. I think this is an oversight on the clojure side, but well ...

**Comment by bbatsov** [comment]
This was fixed by @alexander-yakushev recently.

**Comment by Macroz** [comment]
This is not fixed for example for e.g. `cider-pprint-eval-last-sexp`
