### ISSUE TITLE
various image content-type does not work

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2277]
## Expected behavior

CIDER REPL should display image like this example https://github.com/clojure-emacs/cider/issues/1510#issuecomment-373988901

## Actual behavior

CIDER print object only:

```
user> (do (println "foo")
    (binding [*out* *err*]
      (println "bar"))
    (println "baz")
    (clojure.java.io/file "~/Pictures/Beauty/2015-05-04 070354.jpg"))
foo
bar
baz
;; => #object[java.io.File 0x2f763da "~/Pictures/Beauty/2015-05-04 070354.jpg"]
user> (clojure.java.io/file "~/Pictures/Beauty/2015-05-04 070354.jpg")
;; => #object[java.io.File 0x1aa925f6 "~/Pictures/Beauty/2015-05-04 070354.jpg"]
```

### CIDER version information

```
;; CIDER 0.17.0snapshot (package: 20180428.658), nREPL 0.2.12
;; Clojure 1.8.0, Java 9.0.4
```

### Emacs version

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-04-22

### Operating system

Arch Linux

**Comment by arrdem** [comment]
What are your configured `cider-repl-use-pretty-printing` and `cider-repl-use-content-types` custom var values?

The content-type support works by intercepting the result of an nREPL `eval` op, and adding to the eval op. Unfortunately, the pretty-printing middleware works basically the same way - and the pretty printing middleware deliberately removes the response data which the content-type middleware looks for. This means that if you have both the pretty printer and the content-type logic on at once weirdness happens. You may get both behaviors, you may only get the pretty printing behavior.

The real fix here is to rework the pretty printing middleware so that it won't discard the `:value` response that the content-type middleware needs, and to augment the cider-repl handler logic to simply discard the eval result when pretty printing.

As a workaround, I suggest turning off the pretty-printing features in your `custom` configuration. This seems to prevent CIDER from enabling that codepath on REPL startup, and makes `M-x cider-repl-toggle-content-types` behave predictably.

**Comment by stardiviner** [comment]
`cider-repl-use-pretty-printing` is `nil`. `cider-repl-use-content-types` is `t`.
After upgrading CIDER to latest version on Emacs MELPA. and try upper demo clojure example code. still same result.

**Comment by dpsutton** [comment]
happy to say that it worked for me:

```

**Comment by dpsutton** [comment]
So one thing I've noticed however.

After I put an image in the repl, the behavior after can be quite strange. When I open up a new paren to type a form after, sometimes it says there are unbalanced parens. And it seems to consistently go into endless garbage collection that I have to halt with `C-g`.

![brutal](https://user-images.githubusercontent.com/6377293/39704892-6e33c26a-51d2-11e8-9315-08bb60ffb3c7.png)

This is from the memory profiler. I'm not sure what's going on but the parens balancer and figuring out where to start the next sexp are heavily affected by images. Is there a way to mark these image regions as out of bounds for sexp parsing?

**Comment by dpsutton** [comment]
although strangely, it seems to depend upon the image. When I used the above screenshot in the repl it was fine and i could use sexp navigation back and forth over it. The clojure image seems to be an unbalanced parens. I'm on emacs 27 from git so this may be a bug in emacs right now.

![clojure](https://user-images.githubusercontent.com/6377293/39705321-a895053a-51d3-11e8-9cb2-67590a977fd7.png)


I've attached the image if someone wants to confirm

**Comment by stardiviner** [comment]
By your hints, I found I use absolute path to image, it works now. Seems `clojure.java.io/file` requires absolute path.
@dpsutton I tested your image, works fine on my machine, have not your described problem.

**Comment by stardiviner** [comment]
I just found another weird problem. Maybe related to @dpsutton 's problem.
After I executed:
```
user> (clojure.java.io/file "/home/stardiviner/Pictures/Beauty/2015-05-04 070354.jpg")
<IMAGE>
user> (+ 1 1)
|
```
Then the second `(+ 1 1)` is not evaluated, no result. no prompt returned, point is stopped at `|` position.

BTW, how do you guys get that "eval log"?

**Comment by dpsutton** [comment]
@stardiviner check out `m-x nrepl-toggle-message-logging`. then look for a buffer named `"*nrepl-messages %s*"` (the %s is the connection name). check out [hacking cider](http://hackingcider.com/posts-output/2017-04-26-beginning-to-hack-on-cider/) for a bit more.

when you say the prompt is stopped there, do you see a spinner? can you interrupt it with `c-g` or is the process dead? Mine was always garbage collecting and was interruptible. I think I saw on another occasion that the process was killed but I may have manually inserted an image with the emacs `insert-image-file` function.

**Comment by stardiviner** [comment]
Here is my `*nrepl-server*` buffer output:
```
nREPL server started on port 44731 on host 0:0:0:0:0:0:0:0 - nrepl://0:0:0:0:0:0:0:0:44731
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mranderson048.orchard.v0v2v0_20180506v160903_5.dynapath.v0v2v5.dynapath.defaults$eval1918$fn__1919 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of mranderson048.orchard.v0v2v0_20180506v160903_5.dynapath.v0v2v5.dynapath.defaults$eval1918$fn__1919
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

After toggle `nrepl-log-messages`.
Execute `(clojure.java.io/file "/home/stardiviner/Pictures/Beauty/2015-05-04 070354.jpg")` in REPL,
Then execute `(print "hi")`

got output in `*nrepl-message localhost*` buffer:
```
(-->
  id         "1"
  op         "clone"
  time-stamp "2018-05-08 11:38:34.698224611"
)
(<--
  id          "1"
  session     "33fa3c55-57dd-4a0b-ab77-0491291186ad"
  time-stamp  "2018-05-08 11:38:34.745317966"
  new-session "07c655d4-444b-43c4-a695-43a9da90104e"
  status      ("done")
)
(-->
  id         "2"
  op         "clone"
  time-stamp "2018-05-08 11:38:34.757887076"
)
(<--
  id          "2"
  session     "e10f4bdb-fcc0-43b1-a888-617ec0db2b8f"
  time-stamp  "2018-05-08 11:38:34.763576303"
  new-session "64c1f986-0998-4208-9ed6-0305a3b7388f"
  status      ("done")
)
(-->
  id         "3"
  op         "describe"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:34.780042360"
)
(<--
  id         "3"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:34.820461404"
  aux        (dict ...)
  ops        (dict ...)
  status     ("done")
  versions   (dict ...)
)
(-->
  id                       "4"
  op                       "eval"
  session                  "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp               "2018-05-08 11:38:34.851443651"
  code                     "(str *ns*)"
  inhibit-cider-middleware "true"
)
(<--
  id         "4"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:34.880121925"
  ns         "user"
  value      "\"user\""
)
(<--
  id         "4"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:34.922354334"
  status     ("done")
)
(-->
  id                       "5"
  op                       "eval"
  session                  "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp               "2018-05-08 11:38:34.936262254"
  code                     "(when (clojure.core/resolve 'clojure.main/repl-requires)
   ..."
  inhibit-cider-middleware "true"
)
(<--
  id         "5"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:35.078042122"
  ns         "user"
  value      "(nil nil nil)"
)
(<--
  id         "5"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:35.119050369"
  status     ("done")
)
(-->
  id                       "6"
  op                       "eval"
  session                  "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp               "2018-05-08 11:38:35.135765163"
  code                     "(do (set! *print-length* 100))"
  inhibit-cider-middleware "true"
)
(<--
  id         "6"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:35.151465580"
  ns         "user"
  value      "100"
)
(<--
  id         "6"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:35.192226482"
  status     ("done")
)
(-->
  id         "7"
  op         "out-subscribe"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:35.610291966"
)
(-->
  id           "8"
  op           "init-debugger"
  session      "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp   "2018-05-08 11:38:35.629006449"
  print-length 10
  print-length 10
  print-length 10
  print-length 10
  print-level  10
  print-level  10
  print-level  10
  print-level  10
)
(-->
  id               "9"
  op               "version"
  session          "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp       "2018-05-08 11:38:35.670022820"
  debug            "false"
  prefix-rewriting "false"
)
(<--
  id         "9"
  op         "version"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:38:35.701191681"
  status     ("done" "unknown-op" "error")
)
(<--
  id            "7"
  session       "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp    "2018-05-08 11:38:36.397415570"
  out-subscribe "07c655d4-444b-43c4-a695-43a9da90104e"
  status        ("done")
)
(-->
  id           "10"
  op           "eval"
  session      "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp   "2018-05-08 11:40:21.274720514"
  code         "(clojure.java.io/file "/home/stardiviner/Pictures/Beauty/201..."
  column       7
  content-type "true"
  file         "*cider-repl localhost*"
  line         13
  ns           "user"
)
(<--
  id           "10"
  session      "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp   "2018-05-08 11:40:22.474124708"
  body         ""
  content-type ("message/external-body"
 (dict "URL" "file:/home/stardiviner/Pictures/Beauty/2015-05-04%20070354.jpg" "access-type" "URL"))
  ns           "user"
  value        "#object[java.io.File 0x7a9b1498 "/home/stardiviner/Pictures/..."
)
(-->
  id         "11"
  op         "slurp"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:40:22.477718931"
  url        "file:/home/stardiviner/Pictures/Beauty/2015-05-04%20070354.j..."
)
(<--
  id         "10"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:40:22.491979973"
  status     ("done")
)
(<--
  id                        "11"
  session                   "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp                "2018-05-08 11:40:22.841232520"
  body                      "/9j/4SISRXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAA..."
  content-transfer-encoding "base64"
  content-type              ("image/jpeg"
 (dict))
)
(<--
  id         "11"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:40:22.847075218"
  status     ("done")
)
(<--
  id                 "10"
  session            "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp         "2018-05-08 11:40:23.087341349"
  changed-namespaces (dict ...)
  repl-type          "clj"
  status             ("state")
)
(-->
  id         "12"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.375297090"
  context    ":same"
  ns         "user"
  symbol     "pri"
)
(-->
  id         "13"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.433041194"
  context    ":same"
  ns         "user"
  symbol     "pri"
)
(-->
  id         "14"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.436054424"
  context    ":same"
  ns         "user"
  symbol     "pri"
)
(-->
  id         "15"
  op         "eldoc"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.475101568"
  ns         "user"
  symbol     "pri"
)
(-->
  id         "16"
  op         "eldoc"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.477758803"
  ns         "user"
  symbol     "pri"
)
(-->
  id         "17"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.605713978"
  context    ":same"
  ns         "user"
  symbol     "prin"
)
(-->
  id         "18"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.608408869"
  context    ":same"
  ns         "user"
  symbol     "prin"
)
(-->
  id         "19"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.611267310"
  context    ":same"
  ns         "user"
  symbol     "prin"
)
(-->
  id         "20"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.759606138"
  context    ":same"
  ns         "user"
  symbol     "print"
)
(-->
  id         "21"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.814899659"
  context    ":same"
  ns         "user"
  symbol     "print"
)
(-->
  id         "22"
  op         "complete"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:27.817533194"
  context    ":same"
  ns         "user"
  symbol     "print"
)
(-->
  id         "23"
  op         "eldoc"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:28.083150316"
  ns         "user"
  symbol     "print"
)
(-->
  id         "24"
  op         "eldoc"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:29.075207959"
  ns         "user"
  symbol     "hi"
)
(<--
  id         "23"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:29.843523861"
  docstring  "Prints the object(s) to the output stream that is the curren..."
  eldoc      (("&" "more"))
  name       "print"
  ns         "clojure.core"
  status     ("done")
  type       "function"
)
(-->
  id         "25"
  op         "eldoc"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:29.972220486"
  ns         "user"
  symbol     "\266J\206\306\251\347\355"
)
(-->
  id         "26"
  op         "eldoc"
  time-stamp "2018-05-08 11:42:35.941183374"
  ns         "user"
  symbol     "\266J\206\306\251\347\355"
)
(-->
  id           "27"
  op           "eval"
  time-stamp   "2018-05-08 11:42:41.580182208"
  code         "(print \"hi\")"
  column       7
  content-type "true"
  file         "*cider-repl localhost*"
  line         335
  ns           "user"
)
```

**Comment by arrdem** [comment]
@stardiviner .... what's the problem? you can see it do the content-type + slurp handshake in your nREPL trace.

**Comment by stardiviner** [comment]
@arrdem I can see the image now. but following another problem in previous post https://github.com/clojure-emacs/cider/issues/2277#issuecomment-387274226 (Do I need to open a new issue for this?)

**Comment by bbatsov** [comment]
What is this coming from?

```(-->
  id         "25"
  op         "eldoc"
  session    "07c655d4-444b-43c4-a695-43a9da90104e"
  time-stamp "2018-05-08 11:42:29.972220486"
  ns         "user"
  symbol     "\266J\206\306\251\347\355"
)```

**Comment by stardiviner** [comment]
@bbatsov Thanks pointed it out. I figured out how to reproduce this issue now.
Actually cider display image is fine. This weird symbol obvious is from display image which eldoc try to get doc for them.

Toggle nrepl log messaging.
Disable eldoc-mode in CIDER REPL buffer, then display image, then movie point backward around, on the image etc. All things fine, no weird symbol in nrepl log.
Enable eldoc-mode in CIDER REPL buffer, then move point backward around, on the image, then nrepl log displays those weird symbols. then input `(+ 1 1)` does not work any more. even though I disable eldoc-mode again.

**Comment by bbatsov** [comment]
Btw, it also seems strange to me that the behaviour would change with a relative/absolute file path.

**Comment by stardiviner** [comment]
Me too, it supposed work in CIDER (Emacs side) even though `clojure.java.io/file` returned File Object might not work with relative path?

**Comment by stardiviner** [comment]
Forget to update here. I fixed it in commit https://github.com/stardiviner/cider/commit/dfa45aedac2bd5a8a679472652eae49fb389e318

**Comment by arichiardi** [comment]
Is there still an issue with relative/absolute path (I am asking because it seems so to me here)

**Comment by bbatsov** [comment]
No my knowledge there's not such issue - I was actually using relative paths that needed to be expanded by the shell (e.g. `~/img.png`), which is the actual cause of the problem that I experienced. Silly me!
