### ISSUE TITLE
cider-jack-in appears to look for a project.clj despite being set to use clojure-cli

### ISSUE THREAD

**Issue by nivekuil** [clojure-emacs/cider#2896]
## Expected behavior
cider-jack-in works
## Actual behavior
```
{:clojure.main/message
 "Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).\nproject.clj (No such file or directory)\n",
 :clojure.main/triage
 {:clojure.error/class java.io.FileNotFoundException,
  :clojure.error/line -2,
  :clojure.error/cause "project.clj (No such file or directory)",
  :clojure.error/symbol java.io.FileInputStream/open0,
  :clojure.error/source "FileInputStream.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message "Syntax error macroexpanding at (core.clj:20:7).",
    :data
    {:clojure.error/phase :execution,
     :clojure.error/line 20,
     :clojure.error/column 7,
     :clojure.error/source "core.clj"},
    :at [clojure.lang.Compiler$InvokeExpr eval "Compiler.java" 3707]}
   {:type java.io.FileNotFoundException,
    :message "project.clj (No such file or directory)",
    :at [java.io.FileInputStream open0 "FileInputStream.java" -2]}],
  :trace
  [[java.io.FileInputStream open0 "FileInputStream.java" -2]
   [java.io.FileInputStream open "FileInputStream.java" 212]
   [java.io.FileInputStream <init> "FileInputStream.java" 154]
   [clojure.java.io$fn__11496 invokeStatic "io.clj" 229]
   [clojure.java.io$fn__11496 invoke "io.clj" 229]
   [clojure.java.io$fn__11409$G__11402__11416 invoke "io.clj" 69]
   [clojure.java.io$fn__11508 invokeStatic "io.clj" 258]
   [clojure.java.io$fn__11508 invoke "io.clj" 254]
   [clojure.java.io$fn__11409$G__11402__11416 invoke "io.clj" 69]
   [clojure.java.io$fn__11470 invokeStatic "io.clj" 165]
   [clojure.java.io$fn__11470 invoke "io.clj" 165]
   [clojure.java.io$fn__11422$G__11398__11429 invoke "io.clj" 69]
   [clojure.java.io$reader invokeStatic "io.clj" 102]
   [clojure.java.io$reader doInvoke "io.clj" 86]
   [clojure.lang.RestFn invoke "RestFn.java" 410]
   [clojure.lang.AFn applyToHelper "AFn.java" 154]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$slurp invokeStatic "core.clj" 6942]
   [clojure.core$slurp doInvoke "core.clj" 6942]
   [clojure.lang.RestFn invoke "RestFn.java" 410]
   [clojure.lang.AFn applyToHelper "AFn.java" 154]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.lang.Compiler$InvokeExpr eval "Compiler.java" 3702]
   [clojure.lang.Compiler$InvokeExpr eval "Compiler.java" 3701]
   [clojure.lang.Compiler$StaticMethodExpr eval "Compiler.java" 1728]
   [clojure.lang.Compiler$DefExpr eval "Compiler.java" 457]
   [clojure.lang.Compiler eval "Compiler.java" 7182]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 1789]
   [com.billpiel.sayid.nrepl_middleware$eval6187$loading__6721__auto____6188
    invoke
    "nrepl_middleware.clj"
    1]
   [com.billpiel.sayid.nrepl_middleware$eval6187
    invokeStatic
    "nrepl_middleware.clj"
    1]
   [com.billpiel.sayid.nrepl_middleware$eval6187
    invoke
    "nrepl_middleware.clj"
    1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [nrepl.cmdline$require_and_resolve invokeStatic "cmdline.clj" 194]
   [nrepl.cmdline$require_and_resolve invoke "cmdline.clj" 185]
   [nrepl.cmdline$fn__1716 invokeStatic "cmdline.clj" 199]
   [nrepl.cmdline$fn__1716 invoke "cmdline.clj" 199]
   [clojure.core$map$fn__5862$fn__5863 invoke "core.clj" 2742]
   [clojure.core$map$fn__5862$fn__5863 invoke "core.clj" 2742]
   [clojure.lang.PersistentVector reduce "PersistentVector.java" 343]
   [clojure.core$transduce invokeStatic "core.clj" 6883]
   [clojure.core$into invokeStatic "core.clj" 6899]
   [clojure.core$into invoke "core.clj" 6887]
   [nrepl.cmdline$__GT_mw_list invokeStatic "cmdline.clj" 226]
   [nrepl.cmdline$__GT_mw_list invoke "cmdline.clj" 224]
   [nrepl.cmdline$build_handler invokeStatic "cmdline.clj" 235]
   [nrepl.cmdline$build_handler invoke "cmdline.clj" 228]
   [nrepl.cmdline$options__GT_handler invokeStatic "cmdline.clj" 304]
   [nrepl.cmdline$options__GT_handler invoke "cmdline.clj" 295]
   [nrepl.cmdline$server_opts invokeStatic "cmdline.clj" 352]
   [nrepl.cmdline$server_opts invoke "cmdline.clj" 340]
   [nrepl.cmdline$dispatch_commands invokeStatic "cmdline.clj" 443]
   [nrepl.cmdline$dispatch_commands invoke "cmdline.clj" 436]
   [nrepl.cmdline$_main invokeStatic "cmdline.clj" 459]
   [nrepl.cmdline$_main doInvoke "cmdline.clj" 454]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "project.clj (No such file or directory)",
  :phase :execution}}
```
## Steps to reproduce the problem
Try a directory with 2 files:

/tmp/deps.edn
/tmp/test.clj

If you add a project.clj, the cider menu to choose pops up and if you choose clojure-cli then it still appears to try to parse the project.clj file, returning an IndexOutOfBoundsException instead for with an invalid project.clj.

### CIDER version information

"0.26.1"

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-24

### Operating system

Arch Linux

**Comment by bbatsov** [comment]
If you take a closer look at the stacktrace you'll see the error is coming from sayid. You can disable it to solve your problem. The actual error is that sayid can't get its own version number from its own `project.clj` file which is weird.

**Comment by nivekuil** [comment]
Maybe it's https://github.com/clojure-emacs/sayid/commit/cbc3546fb6b1374080f1646ac3a6532a5723b7eb ?

**Comment by nivekuil** [comment]
Oh, this is on an older project I didn't add sayid to in deps.edn, but cider is trying to inject sayid anyway. I think I should default `sayid-inject-dependencies-at-jack-in` to nil, and then enable it on a .dir-locals basis?

**Comment by bbatsov** [comment]
There's a sayid.el extension that you have installed if it's getting injected. That's not part of CIDER, rather a CIDER plugin. You can either remove the package or update its config. 

> Maybe it's clojure-emacs/sayid@cbc3546 ?

Yeah, likely it is, but cider-nrepl uses similar code, so I'm not sure why it's not working properly.

**Comment by wminshew** [comment]
I'm getting the same `project.clj` issue trying to `cider-jack-in` from `cider-scratch`

Cider 0.26.1
MacOS
clojure 1.10.1

**Comment by bbatsov** [comment]
Well, I guess something's wrong with the version extraction logic for sure, but I can't understand how this is working in cider-nrepl and not working for sayid.

**Comment by nivekuil** [comment]
Looks like this is fixed now, thanks :)

**Comment by bbatsov** [comment]
Yeah, that's fixed in the latest sayid release.

**Comment by wminshew** [comment]
hm updated my packages today, still not working but a different error now:

```
Are you sure you want to run `cider-jack-in' without a Clojure project? (y or n) y
[nREPL] Starting server via /Users/wminshew/.asdf/shims/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.1"} com.billpiel/sayid {:mvn/version "0.1.0"} refactor-nrepl {:mvn/version "2.5.0"} cider/cider-nrepl {:mvn/version "0.25.3"}}}' -m nrepl.cmdline --middleware '["com.billpiel.sayid.nrepl-middleware/wrap-sayid", "cider.nrepl/cider-middleware"]'
[nREPL] server started on 59724
[nREPL] Establishing direct connection to localhost:59724 ...
[nREPL] Direct connection to localhost:59724 established
[nREPL] Connection closed unexpectedly (connection broken by remote peer)
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: 
error in process sentinel: Could not start nREPL server: 
```

if anyone has ideas I'd be grateful! in the meantime, simple enough to just connect to a lein repl in the terminal

**Comment by bbatsov** [comment]
I'd suggest running the jack-in command in a terminal, so you'd be able to see the actual error.

**Comment by wminshew** [comment]
more detail below

```
Are you sure you want to run `cider-jack-in' without a Clojure project? (y or n) y
[nREPL] Starting server via /Users/wminshew/.asdf/shims/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.1"} com.billpiel/sayid {:mvn/version "0.1.0"} refactor-nrepl {:mvn/version "2.5.0"} cider/cider-nrepl {:mvn/version "0.25.3"}}}' -m nrepl.cmdline --middleware '["com.billpiel.sayid.nrepl-middleware/wrap-sayid", "cider.nrepl/cider-middleware"]'
[nREPL] server started on 60067
[nREPL] Establishing direct connection to localhost:60067 ...
[nREPL] Direct connection to localhost:60067 established
nrepl-server-sentinel: Could not start nREPL server: nREPL server started on port 60067 on host localhost - nrepl://localhost:60067
Execution error (FileNotFoundException) at java.io.FileOutputStream/open0 (FileOutputStream.java:-2).
.nrepl-port (Read-only file system)

```

```
{:clojure.main/message
 "Execution error (FileNotFoundException) at java.io.FileOutputStream/open0 (FileOutputStream.java:-2).\n.nrepl-port (Read-only file system)\n",
 :clojure.main/triage
 {:clojure.error/class java.io.FileNotFoundException,
  :clojure.error/line -2,
  :clojure.error/cause ".nrepl-port (Read-only file system)",
  :clojure.error/symbol java.io.FileOutputStream/open0,
  :clojure.error/source "FileOutputStream.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.io.FileNotFoundException,
    :message ".nrepl-port (Read-only file system)",
    :at [java.io.FileOutputStream open0 "FileOutputStream.java" -2]}],
  :trace
  [[java.io.FileOutputStream open0 "FileOutputStream.java" -2]
   [java.io.FileOutputStream open "FileOutputStream.java" 291]
   [java.io.FileOutputStream <init> "FileOutputStream.java" 234]
   [clojure.java.io$fn__11498 invokeStatic "io.clj" 230]
   [clojure.java.io$fn__11498 invoke "io.clj" 230]
   [clojure.java.io$fn__11435$G__11404__11442 invoke "io.clj" 69]
   [clojure.java.io$fn__11472 invokeStatic "io.clj" 166]
   [clojure.java.io$fn__11472 invoke "io.clj" 166]
   [clojure.java.io$fn__11448$G__11400__11455 invoke "io.clj" 69]
   [clojure.java.io$writer invokeStatic "io.clj" 119]
   [clojure.java.io$writer doInvoke "io.clj" 104]
   [clojure.lang.RestFn invoke "RestFn.java" 410]
   [clojure.lang.AFn applyToHelper "AFn.java" 154]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$spit invokeStatic "core.clj" 6954]
   [clojure.core$spit doInvoke "core.clj" 6954]
   [clojure.lang.RestFn invoke "RestFn.java" 425]
   [nrepl.cmdline$save_port_file invokeStatic "cmdline.clj" 422]
   [nrepl.cmdline$save_port_file invoke "cmdline.clj" 412]
   [nrepl.cmdline$dispatch_commands invokeStatic "cmdline.clj" 447]
   [nrepl.cmdline$dispatch_commands invoke "cmdline.clj" 436]
   [nrepl.cmdline$_main invokeStatic "cmdline.clj" 459]
   [nrepl.cmdline$_main doInvoke "cmdline.clj" 454]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause ".nrepl-port (Read-only file system)"}}
```

is that more helpful?

**Comment by bbatsov** [comment]
Yep. Seems nREPL can't write it's `.nrepl-port` file because the filesystem is read-only. That's completely unrelated to the sayid issue in this ticket.
