### ISSUE TITLE
buffer handling is 'strange'

### ISSUE THREAD

**Issue by arohner** [clojure-emacs/cider#955]
Sorry this isn't more specific, I don't really understand what's going on. 

After upgrading from Cider 0.6 to 0.8.2, buffer handling is strange. A few behaviors I've noticed:

- If M-x cider-connect, restart the JVM and cider-connect to the same host & port, Cider usually creates a new buffer, rather than reusing the old buffer
- The cider buffer name appears based on the path of the file in the active buffer, which may have no relation to the connection
- cider-connect often fails to connect properly if old cider-connect buffers are around. After killing the old buffers, cider-connect works fine.

**Comment by arohner** [comment]
`; CIDER 0.8.2 (Java 1.8.0, Clojure 1.6.0, nREPL 0.2.6)`

**Comment by bbatsov** [comment]
> If M-x cider-connect, restart the JVM and cider-connect to the same host & port, Cider usually creates a new buffer, rather than reusing the old buffer

Pretty sure this was the behaviour in 0.6 as well. Implementing some smarter "reconnect" has been in the to-do list for a while.

> The cider buffer name appears based on the path of the file in the active buffer, which may have no relation to the connection

Yes, this is a known issue that we'll address at some point (the REPL buffers will serve as the connection). This has also been like this for quite a while. @vspinu did some work in this direction, but there's lot more to be done.

> cider-connect often fails to connect properly if old cider-connect buffers are around. After killing the old buffers, cider-connect works fine.

If you find a reliable way to reproduce this problem we'll certainly try to fix it.

**Comment by vspinu** [comment]
>>   The cider buffer name appears based on the path of the file in the active buffer, which may have no relation to the connection

> Yes, this is a known issue that we'll address at some point (the REPL buffers will serve as the connection)

I don't quite understand the problem. REPL buffer contains the name of the project if a new nREPL server is cranked with `cider-jack-in`. For connections I see `host:12345` in the name. No project name or directory name.

**Comment by bbatsov** [comment]
The problem is that you can change the active connection and this won't be reflected in the buffer's name - meaning that extra info in the has little value in practice when dealing with multiple connections. I think we discussed this in the past and I suggested that changing the active connection should not affect REPL buffers and that the active connection should be displayed in the mode-line for source buffers.

**Comment by arohner** [comment]
>  The cider buffer name appears based on the path of the file in the
> active buffer, which may have no relation to the connection
>
> Yes, this is a known issue that we'll address at some point (the REPL
> buffers will serve as the connection)
>
> I don't quite understand the problem. REPL buffer contains the name of the
> project if a new nREPL server is cranked with cider-jack-in. For
> connections I see host:12345 in the name. No project name or directory
> name.
>
>
>
What I'm seeing is that the repl buffer is named for the directory of the
file I'm looking at, *not* the project. i.e. I'm viewing
myproject/src/foo/bar.clj, I M-x cider-connect, and the buffer is
*cider-repl foo*, not *cider-repl myproject*.

**Comment by arohner** [comment]
On Thu, Jan 22, 2015 at 4:42 AM, Bozhidar Batsov <notifications@github.com>
wrote:

> If M-x cider-connect, restart the JVM and cider-connect to the same host &
> port, Cider usually creates a new buffer, rather than reusing the old buffer
>
> Pretty sure this was the behaviour in 0.6 as well. Implementing some
> smarter "reconnect" has been in the to-do list for a while.
>

IIRC the old behavior is that the connection started with *nrepl*, and then
went to *nrepl*<2>, *nrepl*<3>, etc for each new connection. Because the
buffer name didn't change, reconnecting 'just worked'.

I wonder if the change to include the project name in the buffer name is
responsible?

**Comment by vspinu** [comment]
>  I'm viewing myproject/src/foo/bar.clj, I M-x cider-connect, and the buffer is *cider-repl foo*, not *cider-repl myproject*.

That sounds like a bug. I cannot reproduce on linux. It might be OS specific.

> I wonder if the change to include the project name in the buffer name is responsible?

Probably not. On `cider-connect` there is no directory in the REPL buffer name. So the name should be the same, but that doesn't help. I have just tried  that. If jvm is restarted on the server, on the connection side, cider doesn't realize that the connection was lost and even asks for confirmation.  This particular one should be easy to fix. I will look into it.

**Comment by vspinu** [comment]
@arohner, I am fixing the dead-process reuse issue. 

For the repl buffer-name issue I have no idea. I never had the issue you are describing.  Try `M-: (nrepl-project-directory-for (nrepl-current-dir))` and see if it indeed returns right project directory.

**Comment by arohner** [comment]
`(nrepl-project-directory-for (nrepl-current-dir))` returns nil, and
`(nrepl-current-dir)` returns nil

**Comment by vspinu** [comment]
> `(nrepl-project-directory-for (nrepl-current-dir))` returns nil, and `(nrepl-current-dir)` returns nil

To make it clear, you try this in a file inside a project and you get nil, right? 

`nrepl-current-dir` is a very simple function and I don't see how this is possible in current cider.  Something is amiss with your installation I would say.

**Comment by bbatsov** [comment]
@arohner Try evaluating the Emacs Lisp code using `M-:` while visiting some file in the project.

**Comment by arohner** [comment]
Ah ok, I get correct values when the cursor is in the file, but nil when
the cursor is in the repl created by M-x connect.

Using the previous example of myproject/src/foo/bar.clj

Interesting, that (nrepl-project-directory-for (nrepl-current-dir))
correctly returns 'myproject', but the repl is named *cider-repl foo*

**Comment by expez** [comment]
@arohner are these all fixed now?

**Comment by arohner** [comment]
Using cider 4e1d14f1cca7134cf2328b7afa1ac59e9e2210c2, dated April 12, it's not fixed yet. I remember the behavior being better, and different, but not correct. I'll try to repro the issue again.

**Comment by arohner** [comment]
Ok, here's an issue I just hit. I commonly have two repls open, one for CLJ, one for CLJS. I'm using figwheel for the cljs nrepl. One buffer is nrepl'd into the CLJ process on port 6005, second is open to figwheel on 7888. I restart both processes. I M-x cider-connect back into 6005, and everything works fine. I M-x cider-connect into the second one, and the second buffer is 'broken'. Cider said I'm connected successfully, but there's no repl prompt in the *cider-repl localhost*<2> buffer. Attempting to kill *cider-repl localhost*<2> reports "Buffer has a running process; kill it?". Killing the connection and reconnecting often fixes it.

**Comment by arohner** [comment]
This is still broken for me:

`; CIDER 0.9.0snapshot (Java 1.8.0, Clojure 1.7.0-beta3, nREPL 0.2.10)`
running cider vendor'd to c6e57f9013899304b3f36a5b8ec3e4471b9d5a2b

Now, however, the problem is permanent; previously *sometimes* disconnecting and reconnecting fixed the problem, now I haven't found a way to have two connections at the same time.

**Comment by vspinu** [comment]
> Ok, here's an issue I just hit. 

Could you please open a new issue for this one. In OP you described at least 2 problems. One was fixed, the second one we could never reproduce. This new one seems different from your original problems.

**Comment by arohner** [comment]
I opened a second issue here: https://github.com/clojure-emacs/cider/issues/1122
